namespace: ansible
name: gitlab
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.misc: '>=1.0'
repository: git@github.com:coll-test/ansible.gitlab.git
documentation: https://github.com/coll-test/ansible.gitlab/tree/master/docs
homepage: https://github.com/coll-test/ansible.gitlab
issues: https://github.com/coll-test/ansible.gitlab/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
